### ISSUE TITLE
Using multiple bboxes in CounTR

### ISSUE THREAD

**Issue by semisami** [tamnguyenvan/vision-counter#1]
Hello, thank you for your efforts
In using CounTR, how can we use multiple bboxes?
like this:

bboxes = [[[0, 0], [0, 0]], [[1, 1], [1, 1]]]

**Comment by tamnguyenvan** [comment]
Hello @semisami, Sorry for the late reply. Currently, the model only supports 1 input bounding box. If you want a different number of input bounding boxes, you will need to export the ONNX model with a different value.
